command_prefix = ""

[backend]
client_id = "GANBot"
host = "localhost"
port = 8188
webhost = "brage.info"
webdir = "web"
webdir_internal = "GAN/ganbot2"

[database]
path = "ganbot.sqlite3"

[[irc]]
server = "irc.rizon.net"
port = 6697
nick = "GANBot"
channels = ["#nanoha", "#nanobot", "#dess"]

[[irc]]
server = "irc.libera.net"
port = 6697
nick = "GANBot"
channels = ["#questionablebotting", "#questionablequesting"]

[aliases]
default = "sdxl_0.9"
Anime = "waifuxl"

[models."sdxl_0.9"]
workflow = "workflow-sdxl.json.tmpl"
baseline = "sd_xl_base_0.9.safetensors"
refiner = "sd_xl_refiner_0.9.safetensors"
default_positive = ""
default_negative = "deformed, unrealistic, bad quality, grainy, noisy, plastic, hazy, low contrast, monochrome"

[models.waifuxl]
workflow = "workflow-sdxl.json.tmpl"
baseline = "wdxl-aesthetic-0.9.safetensors"
refiner = "sd_xl_refiner_0.9.safetensors"
default_positive = ""
default_negative = "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name"
